---

- name: Check if DisasterRecord Exists
  stat:
    path: ~/workspace/DisasterRecord/README.md
  register: DisasterRecord_init

- name: Check if DisasterRecord VE Exists
  stat:
    path: ~/workspace/DisasterRecord/bin/activate
  register: DisasterRecordVE_init

- name: Clone DisasterRecord
  git:
    repo: https://github.com/shrutikar/DisasterRecord.git
    dest: ~/workspace/DisasterRecord
    version: integration
  when: DisasterRecord_init.stat.exists == False

- name: Create DisasterRecord virtualenv
  command: virtualenv -p python3 ~/workspace/DisasterRecord
  when: DisasterRecordVE_init.stat.exists == False

- name: Copy control scripts to ~
  copy: src={{ item }} dest=~ owner=root group=root mode=0755
  with_items:
    - startDR-All
    - killDR-All
    - startDR-Frontend
    - killDR-Frontend
    - startTStreamMan
    - killTStreamMan
    - startTC
    - killTC
    - startINF
    - killINF
    - startOBJ
    - killOBJ
