---

- hosts: all
  tasks: []

- name: Create workspace
  hosts: api
  become: yes
  roles:
    - codebase_common
  tags:
    - codebase_common

- name: Setup LNEx
  hosts: api
  become: yes
  roles:
    - codebase_lnex
  tags:
    - codebase_lnex

- name: DisasterRecord Provision
  hosts: api
  become: yes
  roles:
    - codebase_dr
  tags:
    - codebase_dr

- name: Setup DisasterRecord Core
  hosts: api
  become: yes
  roles:
    - codebase_dr_core
  tags:
    - codebase_dr_core

- name: Setup DisasterRecord Static Files
  hosts: api
  become: yes
  roles:
    - codebase_dr_static
  tags:
    - codebase_dr_static

- name: Setup DisasterRecord Image Inference Service
  hosts: api
  become: yes
  roles:
    - codebase_dr_inference
  tags:
    - codebase_dr_inference

- name: Setup DisasterRecord Object Detector Service
  hosts: api
  become: yes
  roles:
    - codebase_dr_objectdet
  tags:
    - codebase_dr_objectdet

- name: Setup DisasterRecord Text Classifier Service
  hosts: api
  become: yes
  roles:
    - codebase_dr_textclass
  tags:
    - codebase_dr_textclass

- name: Setup API
  hosts: api
  become: yes
  roles:
    - codebase_api
  tags:
    - codebase_api